services:
  - docker

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

install:
  - export IMAGE_TAG=$(echo "$TRAVIS_COMMIT" | head -c7)
  - echo "$SERVICE_ACCOUNT_KEY" | base64 --decode > ${HOME}/service-account-key.json
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components install kubectl
  - gcloud auth activate-service-account $SERVICE_ACCOUNT --key-file=${HOME}/service-account-key.json
  - gcloud container clusters get-credentials prod --project $PROJECT --zone $ZONE
  - kubectl config set-context --current --namespace=production
  - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  - helm version
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build . -t sr2020/billingapi:$IMAGE_TAG -t sr2020/billingapi:latest
  - docker push sr2020/billingapi
  - helm upgrade billing helm/billing/ --wait --set image.tag=$IMAGE_TAG

branches:
  only:
  - master
  - dev
