services:
  - docker

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

install:
  - export IMAGE_TAG=$(echo "$TRAVIS_COMMIT" | head -c7)
  - echo "$SERVICE_ACCOUNT_KEY" | base64 --decode > ${HOME}/service-account-key.json
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components install kubectl
  - gcloud auth activate-service-account $SERVICE_ACCOUNT --key-file=${HOME}/service-account-key.json
  - gcloud container clusters get-credentials prod --project $PROJECT --zone $ZONE
  - kubectl config set-context --current --namespace=production

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build . -t sr2020/billingapi:$IMAGE_TAG
  - docker push sr2020/billingapi
  - kubectl set image deployment/billing billing=sr2020/billingapi:$IMAGE_TAG --record
  - kubectl rollout status deployment/billing

branches:
  only:
  - master
