FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

ENV DBHOST=instance.evarun.ru
#ENV POSTGRESQLBILLING_DBNAME=sr2020
ENV POSTGRESQLBILLING_DBNAME=rc_sr2020
ENV POSTGRESQLBILLING_USER=backend
ENV POSTGRESQLBILLING_PASSWORD=kz1x21YB1zYJx
ENV MODELS_MANAGER_URL=http
#ENV http_proxy=http://host.docker.internal:8888/
#ENV https_proxy=https://host.docker.internal:8888/

